### ISSUE TITLE
Generate Docs

### ISSUE THREAD

**Issue by Stebalien** [nicokoch/secret-rs#1]
So, I hate downloading and compiling projects just to read their documentation. [Here's](https://github.com/Stebalien/rust-git-hooks/blob/master/update-docs/post-commit) a post-commit hook I wrote to generate rust docs on commit and put them in a project's gh-pages branch. After pushing the branch to github, you should be able to access the documentation at: https://nicokoch.github.io/secret-rs/secret/

**Comment by nicokoch** [comment]
Done! Thanks for your suggestion.
